export const GHANA_UNIVERSITIES = [
  'University of Ghana',
  'Kwame Nkrumah University of Science and Technology',
  'University of Cape Coast',
  'University of Education, Winneba',
  'University for Development Studies',
  'University of Energy and Natural Resources',
  'University of Mines and Technology',
  'University of Health and Allied Sciences',
  'Ghana Institute of Management and Public Administration',
  'University of Professional Studies, Accra',
  'Accra Technical University',
  'Kumasi Technical University',
  'Takoradi Technical University',
  'Ho Technical University',
  'Cape Coast Technical University',
  'Bolgatanga Technical University',
  'Koforidua Technical University',
  'Tamale Technical University',
  'Sunyani Technical University',
  'Regent University College of Science and Technology',
  'Ashesi University',
  'Central University',
  'Valley View University',
  'Pentecost University',
  'Methodist University College Ghana',
  'Presbyterian University College, Ghana',
  'Catholic University College of Ghana',
  'Christian Service University College',
  'Wisconsin International University College, Ghana',
  'Lancaster University Ghana',
  'Academic City University College',
  'Radford University College',
].sort();
