export const categoryStructure = {
  Fashion: ['Dresses', 'Tops & Shirts', 'Trousers & Jeans', 'Skirts', 'Jackets', 'Footwear', 'Bags', 'Watches', 'Jewelry', 'Accessories', 'Underwears', 'Other Fashion'],
  Electronics: ['Phones', 'Laptops', 'Tablets', 'Headphones', 'Chargers', 'Gaming', 'Accessories', 'Other Electronics'],
  Beauty: ['Skincare', 'Makeup', 'Hair Care', 'Fragrance', 'Tools'],
  Home: ['Furniture', 'Decor', 'Kitchen', 'Bedding', 'Appliances'],
  Sports: ['Gym Wear', 'Jersey', 'Equipment', 'Footwear', 'Accessories'],
  Books: ['Textbooks', 'Novels', 'Magazines', 'Comics'],
  Food: ['Snacks', 'Drinks', 'Fast Food', 'Homemade Meals'],
  Glossary: ['Ingredients', 'Spices & Herbs', 'Condiments & Sauces', 'Packaged Food Products', 'Other Glossary'],
  Services: [
    'Tutoring',
    'Photography',
    'Graphic Design',
    'Writing',
    'Delivery',
    'Repair',
    'Fitness Training',
    'Catering',
    'Beauty Services',
    'Other Services',
  ],
  Other: ['Everything else'],
};